# configure UI ENVs
envs:
  targetNamespace: ${namespace}
  teams:
    ${teams}

# configure UI ingress. If needed: "enabled: true"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  ingressClassName: ""
  hosts:
    - host: ${ingress_host}
      paths: ["/"]
  tls:
  - secretName: ${tlsname}
    hosts:
    - ${ingress_host}
