configuration:
  rebootDays: [mo,tu,we,th,fr]

metrics:
  create: true
  namespace: ${namespace}

service:
  create: true
  port: ${service_port}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "${service_port}"
