---
global:
  rbac:
    enabled: true
commonLabels:
  prometheus: default
defaultRules:
  labels:
    alertmanager: default
  rules:
    alertmanager: true
    etcd: false
    general: true
    k8s: true
    kubeApiserver: false
    kubeApiserverError: true
    kubePrometheusNodeAlerting: true
    kubePrometheusNodeRecording: true
    kubernetesAbsent: false
    kubernetesApps: true
    kubernetesResources: false
    kubernetesStorage: true
    kubernetesSystem: false # Override in /root/config/alertrules/kubernetes_sytem.yaml
    kubeScheduler: false
    network: false # Override in /root/config/alertrules/kubernetes_nodes.yaml
    node: false # Override in /root/config/alertrules/kubernetes_nodes.yaml
    prometheus: true
    prometheusOperator: true
    time: false # Override in /root/config/alertrules/kubernetes_nodes.yaml

alertmanager:
  service:
    type: ClusterIP
  ingress:
    enabled: false
    paths: ["/*"]
  alertmanagerSpec:
    externalUrl: ""
    routePrefix: /
    retention: 720h
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

prometheusOperator:
  createCustomResource: ${prometheus_operator_create_crd}
  configReloaderCpu: 130m
  resources:
    limits:
      cpu: 700m
      memory: 100Mi
    requests:
      cpu: 700m
      memory: 100Mi
  tlsProxy:
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
  # admissionWebhooks:
  #   patch:
  #     podAnnotations:
  #       istio-injection: disabled

prometheus:
  service:
    type: ClusterIP
  
  prometheusSpec:
    externalUrl: ""
    routePrefix: /
    retention: 30d
    retentionSize: 10GB
    additionalScrapeConfigs:
      - job_name: 'envoy-stats'
        metrics_path: /stats/prometheus
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: '.*-envoy-prom'
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:15090
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod_name
    ruleNamespaceSelector: {}
    serviceMonitorSelector:
      matchLabels:
        prometheus: default
    ruleSelector:
      matchLabels:
        alertmanager: default
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  enabled: true
  rbac:
    create: true
  adminUser: admin
  adminPassword: ${grafana_password}
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: ${grafana_org_name}
  persistence:
    enabled: true
    storageClassName: local-storage
    accessModes:
      - ReadWriteOnce
    size: 7Gi
  env:
    GF_AUTH_ANONYMOUS_ENABLED: "true"
    GF_AUTH_ANONYMOUS_ORG_NAME: ${grafana_org_name}
    GF_AUTH_ANONYMOUS_ORG_ROLE: Editor
  initChownData:
    enabled: false
  service:
    type: ClusterIP
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL

coreDns:
  enabled: true
kubeDns:
  enabled: false
  service:
    selector:
      k8s-app: kubedns
kubeScheduler:
  enabled: false
kubeApi:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false