#https://github.com/k8s-at-home/charts/tree/master/charts/home-assistant
#helm install --name home-assistant stable/home-assistant

probes:
  liveness:
    enabled: true
  readiness:
    enabled: true
  startup:
    enabled: true

env:
  TZ: "Europe/Oslo"

service:
  port:
    port: 8123

persistence:
  config:
    enabled: true
    emptyDir: false
    # Persistent Volume Storage Class
    # If defined, storageClassName: <storageClass>
    # If set to "-", storageClassName: "", which disables dynamic provisioning
    # If undefined (the default) or set to null, no storageClassName spec is
    #   set, choosing the default provisioner.  (gp2 on AWS, standard on
    #   GKE, AWS & OpenStack)
    storageClass: "local-storage"
    accessMode: ReadWriteOnce
    size: 5Gi
