serviceAccount:
  create: true

rbac:
  create: true

# If true, create a Prometheus service monitor.
serviceMonitor:
  enabled: false
  additonalLabels: {}

# If Grafana dashboards should be installed for the sidecar to pick up and apply.
dashboards:
  enabled: true

istioNamespace: ${istio_namespace}

controlPlane:
  install: true
  spec:
    profile: demo