image:
  repository: sonarqube
  tag: ${image_tag}

deploymentStrategy:
  type: Recreate

ingress:
  enabled: true
  hosts:
    - name: ${sonar_ingress_host}
  annotations:
    kubernetes.io/ingress.class: traefik

resources:
  requests:
    cpu: 1000m
    memory: 3Gi
  limits:
    memory: 3Gi

service:
  type: ClusterIP
  externalPort: 9000
  internalPort: 9000

persistence:
  enabled: true
  storageClass: "local-storage"
  size: 10Gi
  accessMode: ReadWriteOnce

postgresql:
  persistence:
    storageClass: "local-storage"

# https://docs.sonarqube.org/latest/instance-administration/security/
# sonarSecretKey: sonar-secret
