env:
  TZ: "Europe/Oslo"
  NODE_RED_ENABLE_PROJECTS: true

persistence:
  data:
    enabled: true
    emptyDir: false
    size: 3Gi
    storageClass: local-storage
    accessMode: ReadWriteOnce
    mountpath: /data

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    ingressClassName: traefik
    hosts:
    - host: ${ingress_host}
      paths:
      - path: /
        pathType: Prefix
        service:
          name: ${service_name}
          port: ${service_port}
    tls:
    - hosts:
      - ${ingress_host}
      secretName: ${tls_name}
