env:
  TZ: "Europe/Oslo"
  NODE_RED_ENABLE_PROJECTS: true

persistence:
  data:
    enabled: true
    emptyDir: false
    size: 3Gi
    storageClass: local-storage
    accessMode: ReadWriteOnce
    mountpath: /data
