enableProjects: true

env:
  TZ: "Europe/Oslo"

persistence:
  data:
    enabled: true
    emptyDir: false
    size: 3Gi
    storageClass: local-storage
    accessMode: ReadWriteOnce
    mountpath: /data

service:
  enabled: true
  type: ClusterIP
