## Keycloak authentication parameters
## ref: https://github.com/bitnami/bitnami-docker-keycloak#admin-credentials
##
auth:
  createAdminUser: true
  adminUser: admin
  adminPassword: ""
  managementUser: manager
  managementPassword: ""

proxyAddressForwarding: true

replicaCount: ${replica_count}

extraEnvVars:
- name: KC_HOSTNAME
  value: ${kc_hostname}
- name: KC_CACHE
  value: ${kc_cache_type}
- name: KC_CACHE_STACK
  value: ${kc_cache_stack}
- name: JAVA_OPTS_APPEND
  value: ${java_opts_append}

## Service configuration
##
service:
  type: ClusterIP

## Keycloak ingress parameters
## ref: https://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  enabled: true
  ingressClassName: "nginx"
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: ${ingress_hostname}
  path: /
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  tls: true
  servicePort: http

## @section RBAC parameter
## Specifies whether a ServiceAccount should be created
##
serviceAccount:
  create: true

rbac:
  enabled: true

## @section Other parameters

## Metrics configuration
##
metrics:
  enabled: true

  ## Prometheus Operator ServiceMonitor configuration
  ##
  serviceMonitor:
    enabled: true
    namespace: "monitoring"

## @section Database parameters

## PostgreSQL chart configuration
## ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
##
postgresql:
  enabled: false

## External database configuration
##
externalDatabase:
  host: ${external_database_host}
  user: ${external_database_username}
  password: ${external_database_password}
  database: bitnami_keycloak
