#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

#  -- environment variables. See [frontend config](https://nightly.mealie.io/documentation/getting-started/installation/frontend-config/) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: Europe/Oslo

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    ingressClassName: nginx
    hosts:
    - host: ${ingress_host}
      paths:
      - path: /
        pathType: Prefix
        service:
          name: ${service_name}
          port: 3000
    tls:
    - hosts:
      - ${ingress_host}
      secretName: ${tls_name}

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  api-data:
    enabled: true
    mountPath: /app/data/
    accessMode: ReadWriteOnce
    storageClass: "local-storage"
    size: 10Gi

api:
  #  -- environment variables. See [backend config](https://nightly.mealie.io/documentation/getting-started/installation/backend-config/) for more details.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: Europe/Oslo
