enableProjects: true

timezone: UTC+1

persistence:
  config:
    enabled: true
    size: 3Gi
    storageClass: local-storage
    accessModes: ReadWriteOnce

service:
  enabled: true
  type: ClusterIP

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  labels: {}
  hosts:
    - host: ${ingress_host}
      ## Or a tpl that is evaluated
      # hostTpl: '{{ include "common.names.fullname" . }}.{{ .Release.Namespace }}.{{ .Values.ingress.domainname }}'
      paths:
        - path: /
          # Ignored if not kubeVersion >= 1.14-0
          pathType: Prefix
  tls: []
