enableProjects: true

timezone: UTC+1

persistence:
  config:
    enabled: true
    size: 3Gi
    storageClass: local-storage
    accessModes: ReadWriteOnce

service:
  enabled: true
  type: ClusterIP
