configInline:
  # The address-pools section lists the IP addresses that MetalLB is
  # allowed to allocate, along with settings for how to advertise
  # those addresses over BGP once assigned. You can have as many
  # address pools as you want.
  peers:
    - peer-address: 192.168.79.1
      peer-asn: 65500
      my-asn: 65501
  address-pools:
    - name: default
      protocol: bgp
      addresses:
      - ${network_range}

controller:
  nodeSelector:
    kubernetes.io/os: linux

speaker:
  nodeSelector:
    kubernetes.io/os: linux
